a1 = input("enter a mottos wors one by one:" )
a2 = input("enter a mottos wors one by one:" )
a3 = input("enter a mottos wors one by one:" )
a4 = input("enter a mottos wors one by one:" )
motto = "".join(a1 + a2 + a3 + a4)
date =  int(input("Enter your schools foundations date: "))
month = int(input("Enter the month of your sch foundations months: "))
year = int(input("Enter the year of foundation of your school: "))
compdate = print(date,"/",month,"/",year)
print(motto)
print(compdate)