a = tuple(eval(input("enter the first tuple: ")))
b = tuple(eval(input("enter the first tuple: ")))
c = tuple(eval(input("enter the first tuple: ")))
print(a,type(a))
print(b,type(b))
print(c,type(c))